import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["./src/index.ts"],
    outDir: "./dist",
    external: ["@singlestore/ai", "mysql2"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/api/index.ts"],
    outDir: "./dist/api",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/billing/index.ts"],
    outDir: "./dist/billing",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/column/index.ts"],
    outDir: "./dist/column",
    external: ["@singlestore/ai", "mysql2"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/database/index.ts"],
    outDir: "./dist/database",
    external: ["@singlestore/ai", "mysql2"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/job/index.ts"],
    outDir: "./dist/job",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/organization/index.ts"],
    outDir: "./dist/organization",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/private-connection/index.ts"],
    outDir: "./dist/private-connection",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/query/index.ts"],
    outDir: "./dist/query",
    external: ["mysql2"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/region/index.ts"],
    outDir: "./dist/region",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/secret/index.ts"],
    outDir: "./dist/secret",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/table/index.ts"],
    outDir: "./dist/table",
    external: ["@singlestore/ai", "mysql2"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/team/index.ts"],
    outDir: "./dist/team",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/workspace/index.ts"],
    outDir: "./dist/workspace",
    external: ["@singlestore/ai", "mysql2"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/workspace/private-connection/index.ts"],
    outDir: "./dist/workspace/private-connection",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/workspace-group/index.ts"],
    outDir: "./dist/workspace-group",
    external: ["@singlestore/ai"],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/workspace-group/stage/index.ts"],
    outDir: "./dist/stage",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
  {
    entry: ["./src/workspace-group/storage/index.ts"],
    outDir: "./dist/storage",
    external: [],
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
  },
]);
